# -*- coding: utf-8 -*-
"""Master Heart Attack.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IeBdClYkOSXmuYuRIAnfgWwmDGwHN9sG

#**Heart Attack Dataset**

#Loading Libraries
"""

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from sklearn.preprocessing import LabelEncoder

from scipy.stats import chi2_contingency

"""#Loading the Dataset"""

from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Heart Attack.csv")
df

"""#First 10 rows



"""

df.head(10)

"""#Last 10 rows"""

df.tail(10)

"""#Random Sample/Row"""

df.sample()

"""#Basic Info"""

df.info()

df.shape

df.dtypes

"""#Positive-Negative Count (isBalanced)"""

df.gender.value_counts()            #1 is male and 0 is female

df.age.value_counts()

df.groupby(["gender", "class"]).size()

class_percent = df['class'].value_counts(normalize=True) * 100
print("\nPercentages: \n")
print(class_percent)

"""#Positive-Negetive Visualization"""

df['class'].value_counts().plot(kind='bar', color=['skyblue', 'salmon'])
plt.title('Class Distribution: Negative vs Positive')
plt.xlabel('Class')
plt.ylabel('Count')
plt.xticks(ticks=[0,1], labels=['Positive (1)', 'Negative (0)'], rotation=0)
plt.show()

sns.countplot(x='gender', hue='class', data=df)
plt.title("Positive Negetive Count in Each Genders")
plt.show()

"""#Positive Negative Percentage (Pie Chart)"""

class_counts = df['class'].value_counts()
plt.pie(class_counts, labels=class_counts.index, autopct='%1.1f%%')
plt.title("Positive vs Negative Distribution")
plt.show()

"""#Handling Missing Data"""

df.isnull()

df.isnull().sum()

"""#Statistical Summary"""

df.describe()

df.describe(include="all")

"""#Encoding Categorical Data (Label Encoding)"""

le = LabelEncoder()
df['class'] = le.fit_transform(df['class'])

# OR df['class'] = df['class'].map({'negative': 0, 'positive': 1})

df.head()

df_copy = df
df_copy

"""#MEAN"""

mean_values = df.mean(numeric_only=True)
mean_values

mean_values = df.groupby("class").mean(numeric_only=True)
mean_values

"""#MEDIAN"""

median_values = df.median(numeric_only=True)
median_values

median_values = df.groupby("class").median(numeric_only=True)
median_values

"""#MODE"""

mode_values = df.mode(numeric_only=True).iloc[0]
mode_values

mode_values = df.groupby("class").agg(lambda x: x.mode()[0])
mode_values

"""#Outliers (Box Plot)"""

cols = ["impluse", "glucose", "kcm", "troponin"]

plt.figure(figsize=(12, 10))

for i, col in enumerate(cols, 1):
    plt.subplot(2, 2, i)
    plt.boxplot(df[col].dropna())
    plt.title(f"{col}")
    plt.xlabel(col)
    plt.ylabel("Value")

plt.tight_layout()
plt.show()

cols = ["impluse", "glucose", "kcm", "troponin"]

# Prepare data as a list of series
data = [df[col].dropna() for col in cols]

plt.figure(figsize=(10, 6))
plt.boxplot(data, labels=cols)
plt.title("Boxplots of Selected Columns (All in One Graph)")
plt.xlabel("Columns")
plt.ylabel("Values")
plt.show()

"""#Outlier Removal"""

numeric_cols = df.select_dtypes(include=[np.number]).columns

def remove_outliers_iqr(df, cols):
    df_clean = df.copy()
    for col in cols:
        Q1 = df_clean[col].quantile(0.25)
        Q3 = df_clean[col].quantile(0.75)
        IQR = Q3 - Q1

        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR

        df_clean = df_clean[(df_clean[col] >= lower) & (df_clean[col] <= upper)]

    return df_clean

df_clean = remove_outliers_iqr(df, numeric_cols)

print("Original dataset shape:", df.shape)
print("Dataset shape after removing outliers:", df_clean.shape)

df_clean.head()

"""Since the reduction to dataset is too significant (531 rows removed), we will not remove the outliers.

#Feature Selection
"""

print(df.columns.tolist())              #Column names

x = df.drop("class", axis=1)
x

y = df["class"]
y

print(x.shape, y.shape)

"""#ML Model"""

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

print(x_train.shape, x_test.shape)

model = LogisticRegression(max_iter=1000)

model.fit(x_train, y_train)

y_pred = model.predict(x_test)
y_pred

"""#Model's Performance"""

# Accuracy
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

# Precision
precision = precision_score(y_test, y_pred)
print("Precision:", precision)

# Detailed report
print(classification_report(y_test, y_pred))

"""#Vizualization

#Confusion Matrix
"""

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix (numeric):")
print(cm)

cm = confusion_matrix(y_test, y_pred)

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=['Negative (0)', 'Positive (1)'])

disp.plot(cmap='Blues')
plt.title('Confusion Matrix (My Data)')
plt.show()

"""#Class Distribution"""

df['class'].value_counts().plot(kind='bar', color=['skyblue', 'salmon'])
plt.title('Class Distribution: Negative vs Positive')
plt.xlabel('Class')
plt.ylabel('Count')
plt.xticks(ticks=[0,1], labels=['Positive (1)', 'Negative (0)'], rotation=0)
plt.show()

"""#Histogram"""

df.hist(figsize=(10,8), bins=20, color='lightgreen', edgecolor='black')
plt.suptitle('Distribution of Numeric Features')
plt.show()

"""#Heart Attack Outcome of Each Gender"""

sns.countplot(x='gender', hue='class', data=df)
plt.title("Positive Negetive Count in Each Genders")
plt.show()

"""#Correlation

#Correlation Matrix
"""

print("=== Correlation Matrix ===")
corr_matrix = df.corr(numeric_only=True)
print(corr_matrix)

numeric_df = df.select_dtypes(include=['int64', 'float64'])

corr = numeric_df.corr()

plt.figure(figsize=(12, 8))
sns.heatmap(corr, annot=True, fmt=".2f", cmap='coolwarm')
plt.title("Correlation Matrix Heatmap")
plt.show()

"""#Chi Square Test and P Value"""

df_cat = df.copy()

target = 'class'

print("Chi-Square Test Results:\n")

for col in df_cat.select_dtypes(include=['int64']).columns:
    if col == target:
        continue

    contingency = pd.crosstab(df_cat[col], df_cat[target])
    chi2, p, dof, expected = chi2_contingency(contingency)

    print(f"Feature: {col}")
    print(f"Chi-square: {chi2:.4f}")
    print(f"P-value: {p:.4f}\n")